---
- hosts: all
  become: yes
  become_user: root

  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  tasks:
    - name: Update packages (apt-get update)
      apt:
        update_cache: yes

    - name: Add node
      shell: curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -

    - name: Installing nodejs nginx python-certbot-nginx build-essential
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - nodejs
        - nginx
        - build-essential

    - name: Starting nginx on boot
      service:
        name: nginx
        enabled: yes
        state: started

    - name: Create Project directory
      file:
        path: /var/project
        state: directory

    - name: Clone the application repo
      git:
        repo: https://github.com/HarithJ/Yummy-Recipes-CP4.git
        dest: /var/project/Yummy-Recipes-CP4

    - name: Install project dependencies
      shell:
        chdir: /var/project/Yummy-Recipes-CP4/
        cmd:
          sudo npm install

    - name: Removing nginx default.conf
      command: rm -f /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

    - name: Adding nginx configuration
      shell:
        chdir: /etc/nginx/sites-available/
        creates: default
        cmd: |
          sudo bash -c 'cat > default <<EOF
          server {
              server_name yummyrecipes.ml www.yummyrecipes.ml;
              location / {
                  proxy_pass http://127.0.0.1:3000;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade \$http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host \$host;
                  proxy_cache_bypass \$http_upgrade;
                  proxy_redirect off;
              }
          }
          EOF'
          ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

    - name: Restart nginx
      command: systemctl restart nginx

    - name: Create start script
      shell:
        chdir: /var/project/Yummy-Recipes-CP4/
        creates: startenv.sh
        cmd: |
          cat > startenv.sh <<EOF
          #!/bin/bash

          cd /var/project/Yummy-Recipes-CP4/
          npm start
          EOF
          # sudo chmod 744 /var/project/Yummy-Recipes-CP4/startenv.sh

    - name: Create start service
      shell:
        chdir: /etc/systemd/system/
        creates: reacipe.service
        cmd: |
          cat > reacipe.service <<EOF
          [Unit]
          Description=reacipe startup service
          After=network.target

          [Service]
          User=ubuntu
          ExecStart=/bin/bash /var/project/Yummy-Recipes-CP4/startenv.sh
          Restart=always

          [Install]
          WantedBy=multi-user.target
          EOF
          # sudo chmod 664 /etc/systemd/system/reacipe.service


    - name: Change permissions and start service
      shell: |
        sudo chmod 744 /var/project/Yummy-Recipes-CP4/startenv.sh
        sudo chmod 664 /etc/systemd/system/reacipe.service
        sudo systemctl daemon-reload
        sudo systemctl enable reacipe.service
        sudo systemctl start reacipe.service
