- name: Install uwsgi server into venv
  pip:
    name: uwsgi
    virtualenv: /home/ubuntu/Yummy-Recipes/venv
    virtualenv_python: python3.6

- name: Copy uwsgi settings file so that we can use it to run Yummy-Recipes
  copy:
    src: uwsgi.ini
    dest: /home/ubuntu/Yummy-Recipes/Yummy-Recipes-Ch3

- name: Copy the uwsgi service file so that the app runs in the background
  copy:
    src: yummy-recipes.service
    dest: /etc/systemd/system/

- name: Start the service
  systemd:
    name: yummy-recipes
    state: restarted
    enabled: yes
