- name: Copy the script that configures nginx server to home directory
  copy:
    src: nginx-cloud-init.sh
    dest: /home/ubuntu/

- name: copy the systemd file that would run the nginx config script on boot
  copy:
    src: config-nginx.service
    dest: /etc/systemd/system/

- name: Changing perm of nginx-cloud-init.sh, adding "+x"
  file: dest=/home/ubuntu/nginx-cloud-init.sh mode=a+x

- name: start config-nginx Service
  systemd:
    name: config-nginx
    state: started
    enabled: yes
