---
- hosts: localhost
  become: yes
  roles:
  - {role: 'setup', tags: 'setup'}
  - {role: 'project', tags: 'project'}
  - {role: 'uwsgiServer', tags: 'uwsgi'}
  - {role: 'nginxServer', tags: 'nginx'}
