---
- hosts: localhost
  become: no
  vars:
    ansible_python_interpreter: "/usr/local/bin/python3"
  roles:
     - setup
     - project
     - uwsgiServer
     - manala.cloud-init
     - nginxServer
