---
- hosts: localhost
  become: yes
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  roles:
  - {role: 'setup', tags: 'setup'}
  - {role: 'project', tags: 'project'}
  - {role: 'uwsgiServer', tags: 'uwsgi'}
  - {role: 'nginxServer', tags: 'nginx'}
