---
- name: Ensure ppa exists to install python3.6
  apt_repository: repo=ppa:deadsnakes/ppa

- name: Ensure python3.6 is installed
  apt:
    name: python3.6
    force: yes
    state: present
    update_cache: yes

- name: Ensure build-essential is installed
  apt:
    pkg: build-essential
    force: yes
    state: present
    update_cache: yes

- name: Ensure python3.6-dev is installed
  apt:
    pkg: python3.6-dev
    force: yes
    state: present
    update_cache: yes

- name: Ensure python3-pip, Nginx is installed
  apt:
    name: "{{ item }}"
    force: yes
    state: present
  with_items:
    - python3-pip
    - nginx

- name: Install virtualenv via pip
  pip:
    name: virtualenv
    executable: pip3
